### ISSUE TITLE
Box-sizing might affect Gantt appearance

### ISSUE THREAD

**Issue by alekwisnia** [taitems/jQuery.Gantt#102]
I've noticed that after upgrading CSS against newest Bootstrap, it breaks the grid appearance. This is because of box model used for calculations. This Gantt script uses content-box, while new Bootstrap CSS sets box-sizing to border-box for all elements.
The same problem might appear with some browsers.
The solution proposed is in https://github.com/usmonster/jQuery.Gantt/pull/2

**Comment by nickwuk** [comment]
Has the [css fix](https://github.com/taitems/jQuery.Gantt/commit/2666f300fa68af899361a975952fe00a200df5ef) been applied to the [demo](http://taitems.github.io/jQuery.Gantt/) because if I zoom out in Firefox50 or Chrome54 (not tested others) the days of the week in the header still become missaligned as seen below.
![gantt-demo-after-zoom](https://cloud.githubusercontent.com/assets/7723418/21014014/20e57940-bd54-11e6-8aa7-c38022404967.jpg)

**Comment by usmonster** [comment]
@nickwuk Sorry for the delay. The workaround is applied on the demo page, but the bug you're experiencing is more related to #51.

Neither issue is completely fixed yet, but it's slightly better on master than on the version currently used on the demo page that's live now. Can you please instead try here: http://rawgit.com/taitems/jQuery.Gantt/master/index.html ? There are other, only slightly less subtle issues with some browser zoom levels, but it might be fine for you for now.

There is still some careful work to be done on the two issues, so please feel free to follow #51.

**Comment by nickwuk** [comment]
The [demo](http://rawgit.com/taitems/jQuery.Gantt/master/index.html) seems to zoom nicely - great! Any hints as to what fixed it please, was it just css?
