### ISSUE TITLE
Until 9:30AM previous day is highlighted instead of current day

### ISSUE THREAD

**Issue by vieira** [taitems/jQuery.Gantt#155]
I'm not sure if this is intended, but the previous day is highlighted instead of the current day until about 9:30AM (i.e., at 8:45AM of October 16, October 15 is highlighted).

The problem seems to be in the "weeks"  and the "default" cases in the [switch statement of markNow](/taitems/jQuery.Gantt/blob/1e6ee90ac6c4b0697a5fcd63d8b6feddc92cec7c/js/jquery.fn.gantt.js#L981-L983):

```
var cd = Date.parse(new Date());
// new Date(cd) is Thu Oct 16 2014 09:20:20 GMT+0100 (WEST) which is the current day
 cd = (Math.floor(cd / 36400000) * 36400000);
// new Date(cd) is Wed Oct 15 2014 23:26:40 GMT+0100 (WEST) which is the previous day
```

I'm also a bit confused about the significance of 36400000 (which seems to be 10h06m40s?).

**Comment by orendawlab** [comment]
I will still getting this issue, thought I'd post what fixed it for me in case anyone else is looking (altered in the "markNow" function mentioned above, I changed it in the default switch since that is where it's applicable to me): 
var cd = new Date();
cd.setHours(0,0,0,0);
$(element).find(':findday("' + Date.parse(cd) + '")').removeClass('wd').addClass('today');
 break;
