### ISSUE TITLE
Calculated days off by one

### ISSUE THREAD

**Issue by rgra** [taitems/jQuery.Gantt#168]
Example:
24.03.2015 - 02.04.2015
Current Calculation 
(((dTo/1000)  - (dFrom/1000)) / 86400)
yields:
8.958333333333334
With Math.floor this results in 8 + 1 = 9 days instead of 10

**Comment by usmonster** [comment]
Yeah, this bad calculation is a known problem which manifests when crossing a Daylight Saving time boundary (see #41, #95, #119, ...). The problem date for you is probably actually the 29th of March, 2015, as I imagine that's when DST starts for you. In the U.S., for example, the bug would have manifested if the Gantt item crossed the 8th of March.

Since this has already been reported, I will close this issue, and you can track the bug by subscribing to #41. Thanks again for bringing it up! This is definitely a high-priority bug set to be fixed in an upcoming release.
