### ISSUE TITLE
Customisation of CSS and texts

### ISSUE THREAD

**Issue by jaukia** [taitems/jQuery.Gantt#174]
It would be great if there was a way to customise the styling of the chart without forking the library. Some things that would be useful:

* toggle which buttons are shown
* add text labels, such as "Today" to the current day button
* adjust grid row height
* change background color (currently doable with CSS)
* adjust left panel width (currently doable with CSS)
* adjust how the loader overlay looks and functions — would be great to have a spinner on top of the chart only, not an overlay covering the whole page

**Comment by usmonster** [comment]
Hi @jaukia! These are all reasonable things that users of the plugin might want, though I think most of these can be done with CSS--no need to fork the project.

Pretty much every chart component has a CSS class, so hiding/showing should be straightforward. You should also be able to add text to elements in the way you describe by adding `content` styles to certain `::before` and/or `::after` pseudo elements ([examples](https://css-tricks.com/css-content/)). Row height is also specified in the CSS, though you're right that the background image might not scale accordingly without additional CSS (or perhaps a different image? I haven't checked, but feel free to file this separately if it's an issue for you).

I'm not sure the loader will change functionally, though visual changes can be made via CSS. It does make better sense, though, to only overlay the data panel of chart when zooming (instead of the whole chart), so please make that a separate issue and I'll take a look!

Thanks, and let me know what you think. I'll close this issue in the meantime.
