### ISSUE TITLE
TimeZone issues

### ISSUE THREAD

**Issue by huguesmax** [taitems/jQuery.Gantt#176]
Hello I use jQuery.gantt to show villa reseration
my time zone is UTC+1 ( Paris ) and I send 

{ "to" : "/Date(1434146400000)/", 
"customClass" : "ganttConfirmed", 
"from" : "/Date(1433541600000)/", 
"label" : "PCI PCI", 
"dataObj" : "303" },

from 06/06/2015 to 13/06/2015 ( DD/MM/YYYY)
view is ok

![days](https://cloud.githubusercontent.com/assets/4928314/7896180/1c33f544-06b1-11e5-917c-8327479ed3f9.PNG)

If I change my TimeZone to UTC-5 ( USA ) on my computer, and I send same data,   the view move to 5/06/2015 to 12/06/2015

and the result is wrong

![-1days](https://cloud.githubusercontent.com/assets/4928314/7896183/31d65a86-06b1-11e5-82b5-1d0235cd46cd.PNG)

Someone has a idea how I can solve this problem ?

**Comment by usmonster** [comment]
Hi, and thanks for using the plugin!

When a `to`/`from`date is specified in milliseconds, it defines an absolute moment in time. The display of that time on the chart will be different depending on your time zone. If you want to specify a "local time" (displayed the same way regardless of time zone), you can just directly use a format like `"2015/06/13 00:00"` in your data instead of `"/Date(...)/"`. You can even leave off the time part, in your case, so just `"2015/06/13"` should be fine for your purposes.

(Note: The value is just passed directly to the `Date` constructor, so you can see [this page](http://dygraphs.com/date-formats.html) for an idea of what other string formats should work. This will be in the updated documentation for the next version.)

Please comment if this doesn't answer your question, and I will reopen the issue. Thanks again!

**Comment by huguesmax** [comment]
Thansk for your help
yes it's work .
bye
Hugues.
