### ISSUE TITLE
gantt is not a function

### ISSUE THREAD

**Issue by sparkline-charlie** [taitems/jQuery.Gantt#187]
Hi,

Hope you could assist me on my error that i encountered.

I've tried inserting the gantt code in a function

![image](https://cloud.githubusercontent.com/assets/15224937/11888762/58f040ea-a57c-11e5-86e5-70a201bc05a9.png)

After running the site. It seems encountering this error

![image](https://cloud.githubusercontent.com/assets/15224937/11888771/71a353e8-a57c-11e5-83bc-453aff6ec4c8.png)

Hope you could help me on this.

Thanks!

**Comment by usmonster** [comment]
Hi @sparkline-charlie! It looks like 2 things might be happening.

First, it looks like the plugin might not be loaded at the time when your `generate` function is called. Are you sure about the script load order on your page? (I can't further debug without seeing your markup.)

Second, it looks like the data you want to eventually pass to the plugin might be undefined when you initialize the plugin. This is because you are getting the data in an asynchronous AJAX call, which may not be `done` by the time the Gantt plugin needs the data. You might want to initialize the Gantt inside your `done` callback, or make your `.ajax` call synchronous (by passing the `async: false` option).

Hope this helps! Closing the issue for now--I'll reopen if it turns out to be an issue with the actual plugin. Good luck!
