### ISSUE TITLE
Bars in the middle of cells

### ISSUE THREAD

**Issue by LuigiMdg** [taitems/jQuery.Gantt#222]
Hi..
I can set the bars in the middle of grid cells?
[From this](https://cdn.pbrd.co/images/He3NLil.png)
[To this](https://cdn.pbrd.co/images/He3NM6z6.png)

**Comment by usmonster** [comment]
Hello! Thanks for using the plugin.
I'm not sure your use case, but there's no clean, built-in way to do that today.
One not-so-clean/hacky way to do this is to add a rule somewhere in your page's CSS:
```css
.fn-gantt .bar {
  margin-left: 12px;
}
```
Though there might be some edge cases that could give undesirable effects, so you may want to test it.

Otherwise, depending on your actual need, you may want to follow #47, which will allow the chart items' positioning to more realistically reflect its time bounds.

I'll close this issue for now, but if none of these solutions address your issue, I can reopen it. Hope this helps!

**Comment by LuigiMdg** [comment]
n. 47 is perfect for me.. But the topic is very old..!
You can't update with this feature?
This plugin is very good and can have a good evolution and much stars
