### ISSUE TITLE
Chart CSS is skewed when placed inside a jQueryUI Tabs control

### ISSUE THREAD

**Issue by bculley** [taitems/jQuery.Gantt#48]
I have a page with two working gantt charts, but when I change the page to put them into separate tabs using the jQueryUI Tabs control, the layout is broken for height and the left panel mostly, but it is enough that the rows will not line up with the row headers.

**Comment by justbaron** [comment]
@usmonster I am not using Bootstrap, but still finding issues with the rendering within a jQuery tab.
I have a JSBIN test, which hopefully shows the problem.
https://jsbin.com/gumeyu/edit?html,output

**Comment by usmonster** [comment]
@bculley This has had no feedback in over 3 years(!😱), and after recent quick testing it looks like it's fixed with #102. Closing now, but please feel free to reopen and include a link to a JSFiddle if you find any issue with the version that's currently on master.

Thanks again for using the plugin!
