### ISSUE TITLE
browser zoom

### ISSUE THREAD

**Issue by mike-aungsan** [taitems/jQuery.Gantt#51]
When browser zoom, the chart does not render, correctly, 

Please have  a look demo page with various zoom of the browser such as 110%, 120%, 130%....

Thanks.

**Comment by cormier** [comment]
Hi, I have tested this suggestion by resetting the box-sizing to content-box as suggested in this commit https://github.com/taitems/jQuery.Gantt/commit/2666f300fa68af899361a975952fe00a200df5ef
It seems to me that even with this patch the issue persists, at least in my browser (Firefox 32.0.2)

**Comment by usmonster** [comment]
@cormier The workaround you reference would not fix the issue (there's more to it), but please follow this and/or #102 for updates.

**Comment by cormier** [comment]
@usmonster thanks for the reply and for the information. I'm willing to help and try to implement a fix. You said there's more to it than resetting the box-sizing to content-box: anything specific in mind?
Thanks.

**Comment by Guracao** [comment]
Hi there! I have the same issue as mentioned above. At 100%, 200% and 300% it renders all as it should, everything between is causing the gridlines not longer to be aligned. Just wanted to ask, if theres any progress regarding to this? Thanks in advance!

**Comment by nickwuk** [comment]
Me too on the demo, see #102

**Comment by usmonster** [comment]
@nickwuk (continuing conversation from #102 here) ...it was a combination of CSS and markup fixes, likely done in 5776d00 (along with lots of other stuff). It's still not perfect at certain zoom levels, which is why this issue is still open. Hope this helps!

**Comment by usmonster** [comment]
Reopening after accidental auto-close when I merged a partial fix.

The issue now seems to be strictly limited to the background display at specific browser zoom levels, i.e. anything not a multiple of 25. This is because the background image has a fixed-width border, and so it renders poorly at certain scales (e.g. 80%, 90%, 110%, ...).

This can probably be solved by changing how the background is rendered, e.g. by [using a gradient instead of an image](/taitems/jQuery.Gantt/commit/a6403caace93ad38336e0c60c32cce344e8a3f6a#diff-6a6a912d0c7b55b537768da778032849R104).
