### ISSUE TITLE
Plugin options to manage controls

### ISSUE THREAD

**Issue by mleden** [taitems/jQuery.Gantt#66]
This plugin is awesome.  One missing feature that I am running into, however, is the ability to integrate it easily with an existing UI.  Specifically, if I try to add custom controls the look-and-feel won't match the out-of-the-box icons OR it won't match the rest of my app.  A couple of features might help:
1. Add a plugin option to enable/disable jQuery UI theme support
2. Add a plugin option to hide/show the out-of-the-box controls (for paging, panning, zooming, etc)
3. Add callbacks for the plugin user/webapp developer to create his/her own equivalents to the out-of-the-box controls (for paging, panning, zooming, etc)

Thanks again for all of the great work on this!
-Mark

**Comment by usmonster** [comment]
I think much of this functionality should be doable with plain old CSS, e.g. `.fn-gantt .navigate .nav-[...] { display: none; }` or similar.

Also please note that this is a jQuery plugin, not a jQuery UI plugin. For jQuery UI functionality (including theme support) you may want to follow and/or comment on #160. If that ends up being implemented, it is much more likely that custom controls will be a part of it.

In the meantime I'll close this issue, since I think it's already covered by other ones.
